# Generated by Django 2.1.2 on 2018-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0002_auto_20181206_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactor',
            name='totp_key',
            field=models.CharField(default='', max_length=70),
        ),
    ]
