# Generated by Django 2.1.2 on 2018-12-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0003_auto_20181209_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactor',
            name='totp_key',
            field=models.CharField(default='', max_length=16),
        ),
    ]
