# Generated by Django 2.1.4 on 2018-12-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0004_auto_20181211_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactor',
            name='last_verified_token',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
